name: catshare_gui
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0
  file_picker: ^12.2.0
  path_provider: ^2.1.6
  path: ^1.9.1
  shared_preferences: ^2.5.5
  tray_manager: ^0.5.3
  window_manager: ^0.5.2
  local_notifier: ^0.1.6
  ffi: ^2.1.4
  win32: ^6.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/app.ico
