import 'package:flutter/material.dart';

enum AppLanguage { english, simplifiedChinese, traditionalChinese }

extension AppLanguageInfo on AppLanguage {
  Locale get locale {
    switch (this) {
      case AppLanguage.english:
        return const Locale('en');
      case AppLanguage.simplifiedChinese:
        return const Locale('zh', 'CN');
      case AppLanguage.traditionalChinese:
        return const Locale('zh', 'TW');
    }
  }

  String get label {
    switch (this) {
      case AppLanguage.english:
        return 'English';
      case AppLanguage.simplifiedChinese:
        return '简体中文';
      case AppLanguage.traditionalChinese:
        return '繁體中文';
    }
  }
}

String appText(AppLanguage language, String key) {
  const values = {
    'en': {
      'receive': 'Receive',
      'send': 'Send',
      'settings': 'Settings',
      'general': 'General',
      'launchAtStartup': 'Launch at startup',
      'startMinimized': 'Start minimized',
      'destination': 'Destination',
      'browse': 'Browse',
      'quickSave': 'Quick Save',
      'systemTray': 'System Tray',
      'appearance': 'Appearance',
      'network': 'Network & System',
      'language': 'Language',
      'chooseLanguage': 'Choose the application language',
      'closeTray': 'Close to tray',
      'closeTrayHint':
          'Keep the app running in the notification area when closing the window',
      'minimizeTray': 'Minimize to tray',
      'minimizeTrayHint': 'Hide window to the tray icon when clicking minimize',
      'receiveSuccessNotification': 'Receive completion dialog',
      'receiveSuccessNotificationHint':
          'Show a dialog when a file transfer completes while OShare is open',
      'desktopDropTarget': 'Desktop drop target',
      'desktopDropTargetHint':
          'Show a floating file drop panel in the bottom-right corner of the desktop',
      'desktopDropTitle': 'Drag files here to send to your phone',
      'desktopDropNoDevices': 'No nearby phones found',
      'desktopDropSelectDevice':
          'Select a phone below to send the dropped files',
      'desktopDropReleaseToSend': 'Release to send files',
      'desktopDropUnavailable': 'Drag and drop is unavailable during transfer',
      'desktopDropStagingFailed': 'Could not prepare the dropped files.',
      'desktopDropSendFailed': 'Could not send the dropped files.',
      'desktopDropStagedSummary': 'Files ready to send',
      'desktopDropCancelStaged': 'Cancel staged files',
      'desktopDropTransfer': 'Transferring files',
      'desktopDropCancelFailed': 'Could not cancel the transfer.',
      'desktopDropTransferCompleted': 'Transfer completed.',
      'desktopDropTransferCancelled': 'Transfer cancelled.',
      'transferSpeed': 'Speed',
      'transferEta': 'ETA',
      'desktopDropFiles': 'files',
      'theme': 'Theme',
      'themeHint': 'Choose your preferred appearance',
      'accentColor': 'Accent color',
      'accentColorHint': 'Pick the app\'s highlight color',
      'accentTeal': 'Teal',
      'accentBlue': 'Blue',
      'accentPurple': 'Purple',
      'accentPink': 'Pink',
      'accentOrange': 'Orange',
      'accentRed': 'Red',
      'accentGreen': 'Green',
      'accentAmber': 'Amber',
      'selection': 'Selection',
      'nearby': 'Nearby devices',
      'file': 'File',
      'folder': 'Folder',
      'add': 'Add',
      'clear': 'Clear',
      'searching': 'Searching for nearby phones...',
      'openPhone':
          'Open 互传 / OShare or OShare on your phone and place it nearby.',
      'quickSaveHint': 'Automatically accept incoming file requests',
      'selectFiles': 'Please select files to send first!',
      'openFolder': 'Open folder in Explorer',
      'logFolder': 'Log folder',
      'openLogFolder': 'Open log folder',
      'off': 'Off',
      'favorites': 'Favorites',
      'on': 'On',
      'dark': 'Dark',
      'light': 'Light',
      'system': 'System',
      'localIp': 'Local IP',
      'transferPort': 'Transfer Port',
      'bridgeServer': 'Bridge Server',
      'protocol': 'Protocol',
      'version': 'Version',
      'found': 'found',
      'files': 'files',
      'receiveActive': 'RECEIVE ACTIVE',
      'receivePaused': 'RECEIVE PAUSED',
      'transferring': 'Transferring files...',
      'receiving': 'Receiving…',
      'receivingFrom': 'Receiving from',
      'nearbyPhone': 'Nearby phone',
      'savedTo': 'Saved to',
      'cancelTransfer': 'Cancel transfer',
      'dismiss': 'Dismiss',
      'close': 'Close',
      'incomingTransfer': 'Incoming Transfer',
      'wantsToSend': 'wants to send',
      'decline': 'Decline',
      'accept': 'Accept',
      'dropFilesHere': 'Drop files or folders here',
      'releaseToAdd': 'Release to add files',
      'dropToSendFiles': 'Drop to send these files',
      'unableToAddDropped': 'Unable to add dropped item',
      'dragDropUnavailable': 'Drag and drop is unavailable during transfer',
      'stagingFailed': 'Could not stage the selected files.',
      'transferFailed': 'Transfer failed',
      'sendFailed': 'Could not send the file.',
      'receiveFailed': 'Could not receive the file.',
      'receiveComplete': 'Receive complete',
      'remoteCancelled': 'The phone cancelled the transfer.',
      'remoteRejected': 'The phone rejected the transfer.',
      'connectionLost': 'The connection to the phone was lost.',
      'transferTimedOut': 'The transfer timed out.',
    },
    'zh-CN': {
      'receive': '接收',
      'send': '发送',
      'settings': '设置',
      'general': '常规',
      'launchAtStartup': '开机启动',
      'startMinimized': '启动时最小化',
      'destination': '保存位置',
      'browse': '浏览',
      'quickSave': '快速保存',
      'systemTray': '系统托盘',
      'appearance': '外观',
      'network': '网络与系统',
      'language': '语言',
      'chooseLanguage': '选择应用语言',
      'closeTray': '关闭到系统托盘',
      'closeTrayHint': '关闭窗口时继续在通知区域运行',
      'minimizeTray': '最小化到系统托盘',
      'minimizeTrayHint': '点击最小化时隐藏到系统托盘',
      'receiveSuccessNotification': '接收完成对话框',
      'receiveSuccessNotificationHint': 'OShare 窗口打开时，文件接收完成后显示对话框',
      'desktopDropTarget': '桌面拖放窗口',
      'desktopDropTargetHint': '在桌面右下角显示浮动文件拖放窗口',
      'desktopDropTitle': '将文件拖到这里以发送到你的手机',
      'desktopDropNoDevices': '未找到附近的手机',
      'desktopDropSelectDevice': '请在下方选择手机以发送拖入的文件',
      'desktopDropReleaseToSend': '松开鼠标以发送文件',
      'desktopDropUnavailable': '传输过程中无法拖放文件',
      'desktopDropStagingFailed': '无法准备拖入的文件。',
      'desktopDropSendFailed': '无法发送拖入的文件。',
      'desktopDropStagedSummary': '文件已准备发送',
      'desktopDropCancelStaged': '取消暂存文件',
      'desktopDropTransfer': '正在传输文件',
      'desktopDropCancelFailed': '无法取消传输。',
      'desktopDropTransferCompleted': '传输已完成。',
      'desktopDropTransferCancelled': '传输已取消。',
      'transferSpeed': '速度',
      'transferEta': '预计剩余',
      'desktopDropFiles': '个文件',
      'theme': '主题',
      'themeHint': '选择你喜欢的外观',
      'accentColor': '主题色',
      'accentColorHint': '选择应用的强调色',
      'accentTeal': '青色',
      'accentBlue': '蓝色',
      'accentPurple': '紫色',
      'accentPink': '粉色',
      'accentOrange': '橙色',
      'accentRed': '红色',
      'accentGreen': '绿色',
      'accentAmber': '琥珀色',
      'selection': '选择文件',
      'nearby': '附近设备',
      'file': '文件',
      'folder': '文件夹',
      'add': '添加',
      'clear': '清除',
      'searching': '正在搜索附近的手机……',
      'openPhone': '请在手机上打开互传 / OShare 或 OShare，并将手机放在附近。',
      'quickSaveHint': '自动接受传入的文件请求',
      'selectFiles': '请先选择要发送的文件！',
      'openFolder': '在资源管理器中打开文件夹',
      'logFolder': '日志文件夹',
      'openLogFolder': '打开日志文件夹',
      'off': '关闭',
      'favorites': '收藏夹',
      'on': '开启',
      'dark': '深色',
      'light': '浅色',
      'system': '跟随系统',
      'localIp': '本地 IP',
      'transferPort': '传输端口',
      'bridgeServer': '桥接服务器',
      'protocol': '协议',
      'version': '版本',
      'found': '个设备',
      'files': '个文件',
      'receiveActive': '接收已开启',
      'receivePaused': '接收已暂停',
      'transferring': '正在传输文件……',
      'receiving': '正在接收……',
      'receivingFrom': '正在接收，来自',
      'nearbyPhone': '附近手机',
      'savedTo': '已保存到',
      'cancelTransfer': '取消传输',
      'dismiss': '关闭',
      'close': '关闭',
      'incomingTransfer': '传入传输',
      'wantsToSend': '想要发送',
      'decline': '拒绝',
      'accept': '接受',
      'dropFilesHere': '将文件或文件夹拖到这里',
      'releaseToAdd': '松开以添加文件',
      'dropToSendFiles': '拖放以发送这些文件',
      'unableToAddDropped': '无法添加拖入的项目',
      'dragDropUnavailable': '传输过程中无法拖放文件',
      'stagingFailed': '无法暂存所选文件。',
      'transferFailed': '传输失败',
      'sendFailed': '无法发送文件。',
      'receiveFailed': '无法接收文件。',
      'receiveComplete': '接收完成',
      'remoteCancelled': '手机已取消传输。',
      'remoteRejected': '手机已拒绝传输。',
      'connectionLost': '与手机的连接已断开。',
      'transferTimedOut': '传输超时。',
    },
    'zh-TW': {
      'receive': '接收',
      'send': '傳送',
      'settings': '設定',
      'general': '一般',
      'launchAtStartup': '開機啟動',
      'startMinimized': '啟動時最小化',
      'destination': '儲存位置',
      'browse': '瀏覽',
      'quickSave': '快速儲存',
      'systemTray': '系統匣',
      'appearance': '外觀',
      'network': '網路與系統',
      'language': '語言',
      'chooseLanguage': '選擇應用程式語言',
      'closeTray': '關閉至系統匣',
      'closeTrayHint': '關閉視窗時繼續在通知區域執行',
      'minimizeTray': '最小化至系統匣',
      'minimizeTrayHint': '點擊最小化時隱藏至系統匣',
      'receiveSuccessNotification': '接收完成對話框',
      'receiveSuccessNotificationHint': 'OShare 視窗開啟時，檔案接收完成後顯示對話框',
      'desktopDropTarget': '桌面拖放視窗',
      'desktopDropTargetHint': '在桌面右下角顯示浮動檔案拖放視窗',
      'desktopDropTitle': '將檔案拖曳到這裡以傳送到你的手機',
      'desktopDropNoDevices': '目前沒有找到附近的手機',
      'desktopDropSelectDevice': '請在下方選擇手機以傳送拖入的檔案',
      'desktopDropReleaseToSend': '放開滑鼠以傳送檔案',
      'desktopDropUnavailable': '傳送過程中無法拖放檔案',
      'desktopDropStagingFailed': '無法準備拖入的檔案。',
      'desktopDropSendFailed': '無法傳送拖入的檔案。',
      'desktopDropStagedSummary': '檔案已準備傳送',
      'desktopDropCancelStaged': '取消暫存檔案',
      'desktopDropTransfer': '正在傳送檔案',
      'desktopDropCancelFailed': '無法取消傳送。',
      'desktopDropTransferCompleted': '傳送已完成。',
      'desktopDropTransferCancelled': '傳送已取消。',
      'transferSpeed': '速度',
      'transferEta': '預計剩餘',
      'desktopDropFiles': '個檔案',
      'theme': '主題',
      'themeHint': '選擇你喜歡的外觀',
      'accentColor': '主題色',
      'accentColorHint': '選擇應用程式的強調色',
      'accentTeal': '青色',
      'accentBlue': '藍色',
      'accentPurple': '紫色',
      'accentPink': '粉色',
      'accentOrange': '橙色',
      'accentRed': '紅色',
      'accentGreen': '綠色',
      'accentAmber': '琥珀色',
      'selection': '選擇檔案',
      'nearby': '附近裝置',
      'file': '檔案',
      'folder': '資料夾',
      'add': '新增',
      'clear': '清除',
      'searching': '正在搜尋附近的手機……',
      'openPhone': '請在手機上開啟互傳 / OShare 或 OShare，並將手機放在附近。',
      'quickSaveHint': '自動接受傳入的檔案請求',
      'selectFiles': '請先選擇要傳送的檔案！',
      'openFolder': '在檔案總管中開啟資料夾',
      'logFolder': '記錄資料夾',
      'openLogFolder': '開啟記錄資料夾',
      'off': '關閉',
      'favorites': '最愛',
      'on': '開啟',
      'dark': '深色',
      'light': '淺色',
      'system': '跟隨系統',
      'localIp': '本機 IP',
      'transferPort': '傳送埠',
      'bridgeServer': '橋接伺服器',
      'protocol': '通訊協定',
      'version': '版本',
      'found': '個裝置',
      'files': '個檔案',
      'receiveActive': '接收已開啟',
      'receivePaused': '接收已暫停',
      'transferring': '正在傳送檔案……',
      'receiving': '正在接收……',
      'receivingFrom': '正在接收，來自',
      'nearbyPhone': '附近手機',
      'savedTo': '已儲存至',
      'cancelTransfer': '取消傳送',
      'dismiss': '關閉',
      'close': '關閉',
      'incomingTransfer': '傳入傳送',
      'wantsToSend': '想要傳送',
      'decline': '拒絕',
      'accept': '接受',
      'dropFilesHere': '將檔案或資料夾拖到這裡',
      'releaseToAdd': '放開以新增檔案',
      'dropToSendFiles': '拖放以傳送這些檔案',
      'unableToAddDropped': '無法新增拖入的項目',
      'dragDropUnavailable': '傳送過程中無法拖放檔案',
      'stagingFailed': '無法暫存選取的檔案。',
      'transferFailed': '傳送失敗',
      'sendFailed': '無法傳送檔案。',
      'receiveFailed': '無法接收檔案。',
      'receiveComplete': '接收完成',
      'remoteCancelled': '手機已取消傳送。',
      'remoteRejected': '手機已拒絕傳送。',
      'connectionLost': '與手機的連線已中斷。',
      'transferTimedOut': '傳送逾時。',
    },
  };
  final code = switch (language) {
    AppLanguage.english => 'en',
    AppLanguage.simplifiedChinese => 'zh-CN',
    AppLanguage.traditionalChinese => 'zh-TW',
  };
  return values[code]?[key] ?? values['en']![key] ?? key;
}
